name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  # Detect which parts of the monorepo changed
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      web: ${{ steps.filter.outputs.web }}
      mobile: ${{ steps.filter.outputs.mobile }}
      supabase: ${{ steps.filter.outputs.supabase }}
      packages: ${{ steps.filter.outputs.packages }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            web:
              - 'apps/web/**'
            mobile:
              - 'apps/mobile/**'
            supabase:
              - 'apps/supabase/**'
            packages:
              - 'packages/**'

  # Type check and lint web app
  check-web:
    name: Check Web App
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.web == 'true' || needs.detect-changes.outputs.packages == 'true'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run type-check --workspace apps/web

      - name: Lint
        run: npm run lint --workspace apps/web

      - name: Build
        run: npm run build --workspace apps/web

  # Type check and lint mobile app
  check-mobile:
    name: Check Mobile App
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.mobile == 'true' || needs.detect-changes.outputs.packages == 'true'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run type-check --workspace apps/mobile

      - name: Lint
        run: npm run lint --workspace apps/mobile

  # Check shared packages
  check-packages:
    name: Check Shared Packages
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.packages == 'true'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check types package
        run: npm run type-check --workspace @workspace/types

      - name: Build types package
        run: npm run build --workspace @workspace/types

      - name: Type check supabase package
        run: npm run type-check --workspace @workspace/supabase

      - name: Build supabase package
        run: npm run build --workspace @workspace/supabase

  # Validate Supabase migrations
  check-supabase:
    name: Check Supabase Migrations
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.supabase == 'true'
    steps:
      - uses: actions/checkout@v4

      - name: Validate migration files
        run: |
          echo "Checking for migration files..."
          if [ -d "apps/supabase/migrations" ]; then
            for file in apps/supabase/migrations/*.sql; do
              if [ -f "$file" ]; then
                echo "Found migration: $file"
                # Basic SQL syntax validation
                if ! grep -q ";" "$file"; then
                  echo "Warning: $file may not contain valid SQL"
                fi
              fi
            done
            echo "Migration validation complete"
          else
            echo "No migrations directory found"
          fi
